attention-dropout: 0
bias-gelu-fusion: false
checkpoint-activations: true
checkpoint-num-layers: 1
data-impl: mmap
distributed-backend: nccl
eval-interval: 1000
eval-iters: 10
fp16:
  enabled: true
  fp16: true
  hysteresis: 2
  loss_scale: 0
  loss_scale_window: 1000
  min_loss_scale: 1
gradient_clipping: 1.0
hidden-dropout: 0
hidden-size: 256
keep-last-n-checkpoints: 4
log-interval: 100
lr-decay-iters: 320000
lr-decay-style: cosine
max-position-embeddings: 2048
model-parallel-size: 1
no-weight-tying: true
norm: layernorm
num-attention-heads: 4
num-layers: 64
optimizer:
  params:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.00299160868252161
  type: Adam
partition-activations: true
pipe-parallel-size: 1
pos-emb: rotary
save-interval: 10000
scaled-upper-triang-masked-softmax-fusion: false
seq-length: 2048
split: 949,50,1
steps_per_print: 10
synchronize-each-layer: true
train-iters: 320000
train_micro_batch_size_per_gpu: 4
wall_clock_breakdown: true
warmup: 0.01
weight-decay: 0
zero_optimization:
  allgather_bucket_size: 500000000
  allgather_partitions: true
  contiguous_gradients: true
  cpu_offload: false
  overlap_comm: true
  reduce_bucket_size: 500000000
  reduce_scatter: true
  stage: 1
